/*
 * Build a `.fbkset` from an extension directory.
 *
 * The pipeline is the app's, moved out of it: bundle `index.ts` into one
 * prebuilt ESM file plus its stylesheet, generate each component's JSON
 * Schema from the author's TypeScript, run every compatibility check, and
 * zip the result with the manifest, the guide, the glyphs and the templates.
 *
 * Two import specifiers are never bundled. `react` (with its jsx runtimes)
 * must come from the app — two Reacts in one page is two renderers, and the
 * platform components would be built by the wrong one. And
 * `@folienbaukasten/platform` resolves to the app's live component surface.
 * Both are replaced by the shims in the ABI bundle, which read the live
 * objects off `globalThis` at load time. Everything else an extension
 * imports IS bundled, and becomes the pack's size.
 */
import { Ajv } from 'ajv';
import { build } from 'esbuild';
import JSZip from 'jszip';
import { createGenerator } from 'ts-json-schema-generator';
import { createHash, createPrivateKey, sign as signBytes } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { SHIMS, abi, packFormat, type SetPackManifest } from './abi.ts';
import { readExtension, type ExtensionSource, type PackConfig } from './config.ts';
import {
  checkGlyph,
  checkIntent,
  checkManifest,
  checkRegistration,
  checkTheme,
  emptyFindings,
  inspectSet,
  merge,
  type Findings,
} from './check.ts';

export interface PackOptions {
  outDir: string;
  overrides?: Partial<PackConfig>;
  /** Ed25519 private key (PEM) and the id it has in the app's trusted list. */
  key?: { file: string; keyId: string };
}

export interface PackResult {
  file: string;
  bytes: number;
  manifest: SetPackManifest;
  findings: Findings;
  signed: boolean;
}

/**
 * The swatch, read from the theme's own stylesheet rather than restated in
 * pack.json: a palette written down twice is a palette that drifts, and the
 * chooser must show the colours the deck will actually use. The first
 * declaration wins — `:root` comes before any narrower override.
 */
function swatchOf(css: string | null): Record<string, string> | undefined {
  if (!css) return undefined;
  const values: Record<string, string> = {};
  for (const [key, token] of Object.entries(abi.swatchTokens)) {
    const m = css.match(new RegExp(`${token}:\\s*([^;]+);`));
    if (!m) return undefined;
    values[key] = m[1]!.trim();
  }
  return values;
}

/**
 * Component metadata with each `schemaType` turned into a JSON Schema.
 *
 * Key order follows `pack.json`'s own — `schemaType` is dropped in place and
 * `schema` appended — so a manifest built here is byte-identical to one the
 * app's packer produced from the same source. That is what makes moving an
 * extension onto this toolkit a verifiable no-op rather than a re-release.
 */
function componentMetas(ext: ExtensionSource, findings: Findings) {
  return (ext.config.components ?? []).map((c) => {
    const meta: Record<string, unknown> = { ...c };
    delete meta.schemaType;
    if (c.glyph) merge(findings, checkGlyph(ext, c.kind, c.glyph));
    if (!c.schemaType) {
      if (c.example !== undefined) {
        findings.warnings.push(
          `component '${c.kind}': an example without a schemaType is unchecked, and the model ` +
            'is shown props it cannot validate against a type',
        );
      }
      return meta;
    }
    const componentsTs = path.join(ext.dir, 'components.ts');
    if (!existsSync(componentsTs)) {
      findings.errors.push(
        `component '${c.kind}': schemaType '${c.schemaType}' needs a components.ts to be ` +
          'generated from',
      );
      return meta;
    }
    const setTsconfig = path.join(ext.dir, 'tsconfig.json');
    if (!existsSync(setTsconfig)) {
      findings.errors.push(
        "an extension needs a tsconfig.json (extend the toolkit's tsconfig.extension.json) — " +
          'the prop schemas are generated by compiling components.ts against it',
      );
      return meta;
    }
    try {
      meta.schema = createGenerator({
        path: componentsTs,
        tsconfig: setTsconfig,
        type: c.schemaType,
        expose: 'export',
        jsDoc: 'extended',
        topRef: false,
        skipTypeCheck: true,
      }).createSchema(c.schemaType);
    } catch (error) {
      findings.errors.push(
        `component '${c.kind}': could not generate a schema for '${c.schemaType}' — ` +
          `${error instanceof Error ? error.message : String(error)}`,
      );
      return meta;
    }
    if (c.example !== undefined) {
      const validate = new Ajv({ strict: false, allErrors: true }).compile(meta.schema as object);
      if (!validate(c.example)) {
        const why = (validate.errors ?? [])
          .map((e) => `${e.instancePath || '(root)'} ${e.message}`)
          .join('; ');
        findings.errors.push(`component '${c.kind}': example does not match its schema: ${why}`);
      }
    }
    return meta;
  });
}

/** Everything checkable about an extension, without writing a pack. */
export async function checkExtension(
  target: string,
  overrides: Partial<PackConfig> = {},
): Promise<{ ext: ExtensionSource; findings: Findings; manifest: SetPackManifest }> {
  const ext = readExtension(target, overrides);
  const findings = emptyFindings();
  merge(findings, checkTheme(ext));
  merge(findings, checkIntent(ext));
  const metas = componentMetas(ext, findings);
  const manifest = manifestOf(ext, metas, []);
  merge(findings, checkManifest(manifest));

  // The registration check needs the built module, so it builds one — into a
  // temporary file, since `check` promises not to produce a pack.
  const tmp = path.join(ext.dir, `.fbk-check-${process.pid}.mjs`);
  try {
    await bundleSet(ext, tmp);
    merge(findings, checkRegistration(ext, await inspectSet(tmp), ext.config.components ?? []));
  } catch (error) {
    findings.errors.push(
      `index.ts does not build: ${error instanceof Error ? error.message : String(error)}`,
    );
  } finally {
    rmSync(tmp, { force: true });
    rmSync(`${tmp.replace(/\.mjs$/, '')}.css`, { force: true });
  }
  return { ext, findings, manifest };
}

/** esbuild over `index.ts`, with the two never-bundled specifiers aliased to
 * the ABI bundle's shims. */
async function bundleSet(ext: ExtensionSource, outfile: string): Promise<void> {
  await build({
    entryPoints: [path.join(ext.dir, 'index.ts')],
    outfile,
    bundle: true,
    format: 'esm',
    target: 'es2022',
    jsx: 'automatic',
    minify: true,
    plugins: [
      {
        /*
         * A root-relative url() in a theme's CSS — /fonts/poppins-400.woff2,
         * /logo.png — names a file the APP serves, not one to copy into the
         * pack. Left as-is it resolves at render time against whatever
         * origin the renderer is on.
         *
         * A plugin rather than `external: ['/*']`: esbuild tests external
         * patterns against resolved absolute paths too, so that pattern also
         * externalised `./theme.css` and the pack came out with no
         * stylesheet. The existsSync guard is what keeps a real absolute
         * path (the shims below) resolving normally.
         */
        name: 'app-served-urls',
        setup(build) {
          build.onResolve({ filter: /^\// }, (args) =>
            existsSync(args.path) ? null : { path: args.path, external: true },
          );
        },
      },
    ],
    alias: {
      react: path.join(SHIMS, 'react.js'),
      'react/jsx-runtime': path.join(SHIMS, 'jsx-runtime.js'),
      'react/jsx-dev-runtime': path.join(SHIMS, 'jsx-runtime.js'),
      '@folienbaukasten/platform': path.join(SHIMS, 'platform.js'),
    },
    logLevel: 'warning',
  });
}

function manifestOf(
  ext: ExtensionSource,
  metas: unknown[],
  templates: { id: string; name: string; description?: string }[],
): SetPackManifest {
  const swatch = swatchOf(ext.themeCss);
  const c = ext.config;
  return {
    formatVersion: abi.packFormatVersion,
    id: ext.id,
    name: c.name ?? ext.id,
    ...(c.description ? { description: c.description } : {}),
    version: ext.version,
    platformAbi: abi.platformAbi,
    ...(c.publisher ? { publisher: c.publisher } : {}),
    ...(c.production ? { production: true } : {}),
    ...(swatch ? { swatch: swatch as SetPackManifest['swatch'] } : {}),
    ...(templates.length ? { templates } : {}),
    ...(c.layoutDescriptions ? { layoutDescriptions: c.layoutDescriptions } : {}),
    ...(ext.provides.length === 1 && ext.provides[0] === 'theme'
      ? {}
      : { provides: ext.provides }),
    ...(metas.length ? { components: metas as SetPackManifest['components'] } : {}),
    ...(c.pptxSafe === false ? { pptxSafe: false } : {}),
  };
}

export async function packExtension(target: string, opts: PackOptions): Promise<PackResult> {
  const ext = readExtension(target, opts.overrides);
  const outDir = path.resolve(opts.outDir);
  const findings = emptyFindings();
  merge(findings, checkTheme(ext));
  merge(findings, checkIntent(ext));
  const metas = componentMetas(ext, findings);

  const stage = path.join(outDir, `.${ext.id}-stage`);
  rmSync(stage, { recursive: true, force: true });
  mkdirSync(stage, { recursive: true });

  await bundleSet(ext, path.join(stage, 'set.js'));

  const stylesheet = path.join(stage, 'set.css');
  if (ext.providesTheme && !existsSync(stylesheet)) {
    findings.errors.push("this theme produced no stylesheet — index.ts must import its theme.css");
  }
  if (!ext.providesTheme && existsSync(stylesheet)) {
    findings.errors.push(
      "this pack provides no theme but imported a stylesheet; a components-only pack's set.css " +
        'would never be linked. Style from the platform tokens instead.',
    );
  }

  /*
   * Inspect a .mjs copy, not set.js itself: the staging directory has no
   * package.json, so Node reads a bare .js as CommonJS and the dynamic
   * import fails — which the check would report as "could not be inspected"
   * rather than as what it is.
   */
  const probe = path.join(stage, '.probe.mjs');
  writeFileSync(probe, readFileSync(path.join(stage, 'set.js')));
  merge(findings, checkRegistration(ext, await inspectSet(probe), ext.config.components ?? []));
  rmSync(probe, { force: true });

  // Starter decks, copied verbatim; each names itself from its own meta, so
  // a template is described where it is written rather than somewhere that
  // can drift from it.
  const templates: { id: string; name: string; description?: string }[] = [];
  const templateDir = path.join(ext.dir, 'templates');
  if (existsSync(templateDir)) {
    mkdirSync(path.join(stage, 'templates'), { recursive: true });
    for (const file of readdirSync(templateDir).filter((f) => f.endsWith('.json')).sort()) {
      const id = path.basename(file, '.json');
      const deck = JSON.parse(readFileSync(path.join(templateDir, file), 'utf8')) as {
        meta?: { title?: string; description?: string; componentSet?: string };
      };
      if (deck.meta?.componentSet && deck.meta.componentSet !== ext.id && ext.providesTheme) {
        findings.warnings.push(
          `template '${id}' names componentSet '${String(deck.meta.componentSet)}', not ` +
            `'${ext.id}' — it will open in another theme`,
        );
      }
      writeFileSync(path.join(stage, 'templates', file), JSON.stringify(deck, null, 2));
      templates.push({
        id,
        name: deck.meta?.title ?? id,
        ...(deck.meta?.description ? { description: deck.meta.description } : {}),
      });
    }
  }

  // Glyphs, copied under a name derived from the kind so two components
  // cannot collide on one file name.
  for (const meta of metas as { kind: string; glyph?: string }[]) {
    if (!meta.glyph) continue;
    const from = path.join(ext.dir, meta.glyph);
    if (!existsSync(from)) continue; // already reported by checkGlyph
    const name = `${meta.kind.replace(/[^a-z0-9]+/gi, '-')}.svg`;
    mkdirSync(path.join(stage, 'glyphs'), { recursive: true });
    writeFileSync(path.join(stage, 'glyphs', name), readFileSync(from));
    meta.glyph = `glyphs/${name}`;
  }

  for (const extra of ['guide.md', 'preview.png']) {
    const from = path.join(ext.dir, extra);
    if (existsSync(from)) writeFileSync(path.join(stage, extra), readFileSync(from));
  }

  const manifest = manifestOf(ext, metas, templates);
  merge(findings, checkManifest(manifest));

  if (findings.errors.length > 0) {
    rmSync(stage, { recursive: true, force: true });
    return { file: '', bytes: 0, manifest, findings, signed: false };
  }
  writeFileSync(path.join(stage, 'manifest.json'), JSON.stringify(manifest, null, 2));

  const files = packFiles(stage).sort();
  const digests: Record<string, string> = {};
  for (const rel of files) {
    digests[rel] = createHash('sha256').update(readFileSync(path.join(stage, rel))).digest('hex');
  }

  if (opts.key) {
    // `--key -` reads the key from stdin, so one kept in a password manager
    // never has to be written to disk to sign with it.
    const key = createPrivateKey(
      readFileSync(opts.key.file === '-' ? 0 : opts.key.file, 'utf8'),
    );
    const signature = {
      algorithm: 'ed25519' as const,
      keyId: opts.key.keyId,
      signature: signBytes(
        null,
        Buffer.from(packFormat.signingPayload(digests), 'utf8'),
        key,
      ).toString('base64'),
    };
    writeFileSync(path.join(stage, 'signature.json'), JSON.stringify(signature, null, 2));
    files.push('signature.json');
  }

  const zip = new JSZip();
  // manifest.json first, so `unzip -p x.fbkset manifest.json` is cheap and
  // the head of the archive says what the file is.
  for (const rel of files.sort((a, b) =>
    a === 'manifest.json' ? -1 : b === 'manifest.json' ? 1 : a.localeCompare(b),
  )) {
    zip.file(rel, readFileSync(path.join(stage, rel)), {
      compression: rel.endsWith('.png') ? 'STORE' : 'DEFLATE',
      // A fixed date keeps two builds of an unchanged extension
      // byte-identical.
      date: new Date(0),
      /*
       * No implicit directory entries. JSZip stamps those with the current
       * time whatever `date` says, which is what stopped two builds of an
       * unchanged extension from being byte-identical — the property the
       * fixed date above exists to give. Install skips directory entries
       * anyway (`if (entry.dir) continue`), and so does every unzip.
       */
      createFolders: false,
    });
  }
  const file = path.join(outDir, `${ext.id}-${ext.version}.fbkset`);
  mkdirSync(outDir, { recursive: true });
  const bytes = await zip.generateAsync({ type: 'nodebuffer' });
  writeFileSync(file, bytes);
  rmSync(stage, { recursive: true, force: true });

  return { file, bytes: bytes.length, manifest, findings, signed: Boolean(opts.key) };
}

function packFiles(dir: string, prefix = ''): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
    const rel = prefix ? `${prefix}/${e.name}` : e.name;
    return e.isDirectory() ? packFiles(path.join(dir, e.name), rel) : [rel];
  });
}
